name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Replace with "master" if your main branch is named master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite builds into the dist folder
          branch: gh-pages # This is the branch where the built site lives